_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 1
                - 41
                - 55
            "2":
                - 1
                - 41
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.11.11
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": darwin-arm64
architecture:
    value: VAE
batch_size:
    value: 64
dataset:
    value: playing_cards_minimal
epochs:
    value: 100
latent_dim:
    value: 100
learning_rate:
    value: 0.0001
seed:
    value: 42
